// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbbV3ZjjwCYKmIQwSnAn44ja37zCM0aRk',
    appId: '1:1000941591331:web:6043acb9749728eca78a96',
    messagingSenderId: '1000941591331',
    projectId: 'startup-31f84',
    authDomain: 'startup-31f84.firebaseapp.com',
    storageBucket: 'startup-31f84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7H2Eq1tjT-37TYfX3jp7jDHPtY4E0FSc',
    appId: '1:1000941591331:android:d3fb65a7873c73b9a78a96',
    messagingSenderId: '1000941591331',
    projectId: 'startup-31f84',
    storageBucket: 'startup-31f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1SzN6KRQdwcm98wx8OPhZLrvXQ_GKGpE',
    appId: '1:1000941591331:ios:858fde256c37312ca78a96',
    messagingSenderId: '1000941591331',
    projectId: 'startup-31f84',
    storageBucket: 'startup-31f84.appspot.com',
    iosClientId: '1000941591331-obn5q1n0m5ng1qtb6gvfq4941raj596b.apps.googleusercontent.com',
    iosBundleId: 'com.mystartupgen.startup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1SzN6KRQdwcm98wx8OPhZLrvXQ_GKGpE',
    appId: '1:1000941591331:ios:858fde256c37312ca78a96',
    messagingSenderId: '1000941591331',
    projectId: 'startup-31f84',
    storageBucket: 'startup-31f84.appspot.com',
    iosClientId: '1000941591331-obn5q1n0m5ng1qtb6gvfq4941raj596b.apps.googleusercontent.com',
    iosBundleId: 'com.mystartupgen.startup',
  );
}
